USE [CobranzasData]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[KeyValue]
(
	[id] [int] IDENTITY(1, 1) NOT NULL,
	[key] [nvarchar](100) NOT NULL,
	[value] [nvarchar](max) NULL,
	[expireAt] [datetime2](7) NULL,
	[createdAt] [datetime2](7) DEFAULT GETUTCDATE(),
	[updatedAt] [datetime2](7) DEFAULT GETUTCDATE()
	CONSTRAINT [PK_KeyValue] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE UNIQUE NONCLUSTERED INDEX [NonClusteredIndex-Key] ON [dbo].[KeyValue]
(
	[key] ASC
)
INCLUDE (
	[id],
	[value],
	[expireAt]
) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO
